language: perl
perl:
  - '5.10'
  - '5.12'
  - '5.14'
  - '5.16'
  - '5.18'
  - '5.20'
addons:
   postgresql: "9.3"
env:
  - DB_TESTING: 1
before_install:
   - "cpanm DBI"
   - "cpanm DBD::Pg"
   - "cpanm Try::Tiny"
   - "cpanm Memoize"
   - "cpanm Test::More"
   - "cpanm Devel::Cover::Report::Coveralls"
script:
   export RELEASE_TESTING=1 && perl Makefile.PL && make test && cover -test -report coveralls
